my_app/urls.py
from  django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    # member
    path('add-member/', views.add_member, name='add-member'),
    path('member-list/', views.member_list, name='member-list'),

    # book
    path('add-book/', views.add_book, name='add-book'),
    path('book-list/', views.book_list, name='book-list'),

    # borrow
    path('add-borrow/', views.add_borrow, name='add-borrow'),
    path('add-borrow/<int:member_id>/', views.add_borrow2, name='add-borrow2'),
    path('borrow-list/', views.borrow_list, name='borrow-list'),
    path('user-book-borrow/<int:member_id>/', views.book_borrow_by_member, name='user-book-borrow'),

    # return
    path('return/', views.return_book_input, name='return-1'),
    path('return/<int:book_id>/', views.return_book, name='return-2'),

    # error success
    path('404/', views.not_found, name='not_found'),
    path('success/', views.success, name='success'),

    # history
    path('history-member/<int:member_id>/', views.history_member, name='history-member'),
    path('history-book/<int:book_id>/', views.history_book, name='history-book'),

    # delete
    path('delete/<str:model>/<int:id>/', views.delete, name='delete'),

    # book lost
    path('book-lost/', views.book_lost_input, name="book-lost-input"),
    path('book-lost/<int:book_id>/', views.book_lost, name='book-lost'),
]

perpus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('', include('django.contrib.auth.urls'))
]

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href=" {% static 'bootstrap/css/bootstrap.min.css' %}">
    {% block style %}
    {% endblock style %}
</head>

<body>
    {% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary text-capitalize">
        <div class="container">

            <a class="navbar-brand" href="{% url 'home:index' %}">
                <h2>Library</h2>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-lg-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            member
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'home:add-member' %}">Add member</a>
                            <a class="dropdown-item" href="{% url 'home:member-list' %}">member list</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Book
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'home:add-book' %}">Add book</a>
                            <a class="dropdown-item" href="{% url 'home:book-list' %}">book list</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            borrowing
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'home:add-borrow' %}">Add borrowing</a>
                            <a class="dropdown-item" href="{% url 'home:borrow-list' %}">list borrowing</a>
                            <a href="{% url 'home:book-lost-input' %}" class="dropdown-item">Book Lost</a>
                            <a href="{% url 'home:return-1' %}" class="dropdown-item">Return</a>
                        </div>
                    </li>
                    <li class="nav-item active text-dark">
                        <a href="{% url 'logout' %}" class="btn btn-outline-danger text-white">logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-fixed-top">
        <a class="navbar-brand ml-5" href="{% url 'home:index' %}">
            <h2>Library</h2>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
            <ul class="navbar-nav ml-lg-auto text-center">
                <li class="nav-item active">
                    <a class="nav-link text-capitalize btn btn-outline-success" href="{% url 'login' %}">Login</a>
                </li>
            </ul>
        </div>
    </nav>
    {% endif %}
    {% block content %}
    {% endblock content %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %} "></script>
</body>

</html>